### ISSUE TITLE
Optimise architecture of database connections

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/knex-migrator#10]
Needs a little bit more love.
1. create test connection when instantiate `knex-migrator`
2. make code more readable for connect/destroy connections to database (this will anyway happen when we add for example the migrations tasks --> more common logic in one place)

**Comment by he8us** [comment]
Hello,

I have the code nearly ready for No. 1. 

There's no way to check the configuration in the instantiation since the only way to connect to the database is to issue a query on it; and that's asynchronous. I don't think the following example is the way to go. Since I'm mainly an in browser JS dev, there's maybe an other way but I don't know it.

```
var KnexMigrator = require('knex-migrator');

new KnexMigrator()
    .then(function(knexMigrator){
        knexMigrator.isDatabaseOK()
    })
    .catch(function(err){
        console.log('Connection problem', err)
    });
```


So my proposal is to introduce a public `checkConnection` method and also call it from `isDatabaseOK` to ensure the credentials and other configuration settings are correct.

What do you think?


he8us

**Comment by kirrg001** [comment]
> There's no way to check the configuration in the instantiation since the only way to connect to the database is to issue a query on it; and that's asynchronous.

Yeah. We can't make a test connection in the constructor.

> So my proposal is to introduce a public checkConnection method and also call it from isDatabaseOK to ensure the credentials and other configuration settings are correct.

Makes sense.

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/knex-migrator/commit/c072fcdbcc4159a3f51cff4d6289722651443d83.
