### ISSUE TITLE
Move from knex CLI to knex-migrator?

### ISSUE THREAD

**Issue by jeff-kilbride** [TryGhost/knex-migrator#56]
Hi, I am currently using the `knex` CLI for migrations, but I would like to start using `knex-migrator`. However, it's not clear from the docs how to handle my existing migration files. For example, should I setup a `/versions/1.0` folder and move my existing migrations into it, then set my `currentVersion` to `1.0`? Does `knex-migrator` use the `knex-migrations` table in the database the same way the `knex` CLI does? Or do I have to start fresh with new migrations specifically for `knex-migrator`? There's not any info in the docs for moving from the `knex` CLI to `knex-migrator`.

Thanks!

**Comment by kirrg001** [comment]
Hey 👋

Before we discuss a possible path, are you aware that Knex CLI and knex-migrator have a different behaviour?

From https://github.com/TryGhost/Ghost/issues/7489

The major downside to knex migrations is that it requires you to cycle through the migrations step by step in order to create a fresh DB. This is designed for long-running single-install software, rather than mass distributed & installed software like Ghost. If we switched to knex migrations in its current form, fresh installs would get slower and slower as time went on.

**Comment by jeff-kilbride** [comment]
Thanks for the quick response! That thread was interesting.

I am currently using the `knex` CLI for my own in-house development with a small team. For development, we run our system locally (including MySQL) inside a set of `docker` containers. For production, we use Amazon RDS instances. It is proprietary code for our own use, not distributed or sold to third parties. So, we are closer to the `long-running single-instance` model. We don't expect anyone to try to install our software and then cycle through the migrations. We use `knex` mainly because it allows us to track our DB changes, along with our code, in our `git` repos. And also to protect against any unforeseen bugs, by allowing us to `rollback` the production server to a previously known state, if necessary.

My issue with the `knex` CLI is that there is no versioning available. All migrations reside in the same directory and there is no easy way to apply a specific set of migrations. The `knex migrate:latest` command just automatically runs all existing migrations that haven't been applied. Worse, the `knex migrate:rollback` command rolls back all migrations from the previously applied batch. On more than one occasion, I have accidentally typed `knex migrate:rollback` and watched an entire batch of previous migrations being stripped away. (Luckily, we test both `up` and `down` thoroughly, so it's never caused any real problems other than frustration...)

I was interested in `knex-migrator`, because you have added a versioning mechanism and have much better organization for the migration files. I'm not sure if it was designed to be used outside the `Ghost` ecosystem, though. Does my use case sound like it would be a good match for `knex-migrator`?

**Comment by kirrg001** [comment]
It's a good use case, but `knex-migrator` doesn't offer a rollback command (yet).

The only feature which is in place right now and Knex CLI offers this i think as well, it will run all migrations of a version in a transaction. So if an error occurs in any of your scripts, they are rolled back.

You could test `knex-migrator` with the following approach (you have suggested most of the steps already).

1. add a `versions/1.0` folder and move all your existing migration files to it.
2. add the `MigratorConfig` to your root and  set `currentVersion` to 1.0 (+ database and migrationPath)
3. npm install -g knex-migrator@latest
4. `knex-migrator` init (will create the migrations table)
3. `knex-migrator health` should show you that that database is healthy, because `knex-migrator` won't execute any of these old migration files, because the `currentVersion` property is set to `1.0`
4. Add a folder `versions/2.0`, add an example migration file.
5. set `currentVersion` to `2.0`
6. `knex-migrator health` should show you that a migration need's to be executed
7. `knex-migrator migrate`

**Comment by jeff-kilbride** [comment]
Ok, thank you! I will give it a try. However, not having a `rollback` command may not work for us.

I appreciate your help.

👍

**Comment by kirrg001** [comment]
Implementing a rollback is not a big deal i think.
Let me know when you have tested `knex-migrator` 👍

**Comment by kirrg001** [comment]
> It's a good use case, but knex-migrator doesn't offer a rollback command (yet).

Knex-migrator [added rollbacks in v3.0.](https://github.com/TryGhost/knex-migrator/blob/master/CHANGELOG.md#300-2017-11-03)
Refs https://github.com/TryGhost/knex-migrator/commit/3ff9139eff98ce30929238ab8a91a35ecc53a1d4.

Closing.
