### ISSUE TITLE
What do you think about supporting "diff" command?

### ISSUE THREAD

**Issue by JasonShin** [TryGhost/knex-migrator#60]
I've just installed knex-migrator and giving it a try. I love how it supports inits and different hooks for migrations (Knex's baked in migration was annoying). I was just having a look at Ghost Github project and it uses schema.js to define db schema. What do you think about knex-migrator starts to support schema.js like in Ghost project and perhaps have "diff" command in cli that automatically creates migration files with necessary upgrades based on schema.js (e.g. update Foo table's Bar column)? 

Below link will give you a better idea of "diff" command that I am talking about
http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/generating_migrations.html

**Comment by JasonShin** [comment]
If you like the idea, I might be able to implement it

**Comment by kirrg001** [comment]
I think the first step here is to document that with knex-migrator it's possible to create a database schema like we have in Ghost - because it's unknown at the moment. Because this is different to other tools. 

I think, the schema doesn't have to be part of KM, a path to the schema is fine for the start in case KM wants to read information from it.

The diff command is a nice idea, but it requires a full spec including how to rollback, how does it get executed automatically (interfere with init/migrate) etc.

**Comment by kirrg001** [comment]
Leaving this issue open, because both the schema and diff idea is interesting.

**Comment by ErisDS** [comment]
Closing as this idea was interesting but ultimately didn't get traction.
